name: drivetransformation
favicon: null
layout_spectrum: 0.6778859451878816
typography_spectrum: 0.2938782114069909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c3279'
    - '#00c09f'
    - '#da0022'
    - '#4c7f8b'
  brandStrength: 0.6449123010970652
  lightness: 0.5820630514062941
  saturation: 0.7510834962595254
  rhythmicContrast: 0.19336244370788336
purpose: []
